### ISSUE TITLE
Underscores stripped from clustered package names

### ISSUE THREAD

**Issue by mortlind** [thebjorn/pydeps#126]
Is there any particular reason why the line of code referenced below strips underscores from clustered package names? It makes the nodes harder to read for me.

https://github.com/thebjorn/pydeps/blob/2c0b958b2f4dd6e00f59b37e63c218d53e6e1773/pydeps/render_context.py#L295

**Comment by thebjorn** [comment]
Ah, an especially well-documented function :-D

If I remember correctly, it is to satisfy the naming constraints on subgraph in graphviz (https://github.com/thebjorn/pydeps/blame/2c0b958b2f4dd6e00f59b37e63c218d53e6e1773/pydeps/render_context.py#L237), but it is probably a bug that the next line uses the cluster id for the label text...

**Comment by mortlind** [comment]
Simply commenting out the `.replace('_', '')`-part of the line solved the problem for me.

**Comment by dd-ssc** [comment]
Any progress on this one ? Any chance this gets fixed in some future release ?

**Comment by thebjorn** [comment]
Check out v1.12.4 available on PyPI.
