### ISSUE TITLE
Collapse target cluster / main package

### ISSUE THREAD

**Issue by mlga** [thebjorn/pydeps#128]
## What
I would like to generate a dependency graph of _my_package_, except, I would also like _my_package_ to be collapsed.

For example, for `pydeps`, instead of that:
![pydeps](https://user-images.githubusercontent.com/24436737/153378392-90963aa1-6d1c-469f-838d-35ca379b5841.png)

I would like to have this:
![pydeps collapsed](https://user-images.githubusercontent.com/24436737/153378430-c784238b-2459-4f5a-8f09-fc2e0a5b32d4.png)

## Why
In a big project, internal module dependencies just clutter generated graph and make it hard to read. I want to visualise the external dependencies tree for developers to have a quick overview of what technical stack is used in _my_package_. I don't care which exact module imports external dependency.

It is already possible? If not, I would gladly try to implement it if you find such a feature valuable. 

Great project btw 😃

**Comment by thebjorn** [comment]
Hi @mlga and thank you for your interest in pydeps!  This sounds like a useful feature.  The closest you can get today is with

    pydeps --cluster --keep-target-cluster <pkgname>

I'm always happy to accept PRs :-)

`--collapse-target-cluster` would probably be a good name for such an option...
