### ISSUE TITLE
sometimes not able to form the dependency graph

### ISSUE THREAD

**Issue by prasanta2018** [thebjorn/pydeps#135]
I've 2 files with exactly same import statements. for one file successfully generated the graph whereas for other it's null.
**these are the import statements:-**
  import sys, os
  from daxpy import *
  from collections import defaultdict
  import functools,types

$ pydeps X/Y/Z-scripts/src/GreValidation.py --include-missing --show-deps
{
    "GreValidation": {
        "bacon": 1,
        "imported_by": [
            "__main__"
        ],
        "name": "GreValidation",
        **"path": null**
    },
    "__main__": {
        "bacon": 0,
        "imported_by": [
            "__main__"
        ],
        "imports": [
            "GreValidation",
            "__main__"
        ],
        "name": "__main__",
        "path": null
    }

path is coming as a null, don't know why. @jhermann @joshkel @miketheman @aroberge

**Comment by thebjorn** [comment]
The lack of formatting makes it very hard to read (hint mark it as code in the editor). I can't reproduce it from here: 
```
(dev36) go|c:\srv\tmp> pydeps pydeps135\GreValidation.py --include-missing --show-deps
{
    "GreValidation": {
        "bacon": 1,
        "imported_by": [
            "__main__"
        ],
        "imports": [
            "collections.defaultdict",
            "daxpy"
        ],
        "name": "GreValidation",
        "path": "c:\\srv\\tmp\\pydeps135\\GreValidation.py"
    },
    "__main__": {
   ...
```

**Comment by prasanta2018** [comment]
Got it @thebjorn , there were some TAB character in the source file, that's why not able to parse by pydeps.
But, proper error logging should be there. That is lacked.
