### ISSUE TITLE
how to get pydeps to capture intermediate imported files

### ISSUE THREAD

**Issue by jspurestore** [thebjorn/pydeps#150]
Hi, I am trying to capture the import relationships from a python program (shbang line, if __name__ == "__main__") to other files in our monorepo. When I ran pydeps on the program file, it just listed the builtins and such and they all had path as null.
command is
pydeps --show-raw-deps --no-output wait.py

running on python3.10. pydeps didn't run on py3.4 or 3.5.

**Comment by jspurestore** [comment]
#!/usr/bin/env python3.4

import enum
from ipaddress import ip_address, IPv6Address
import json
import os
import re
import sys
import time

import requests

sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'ir_lib'))
import ir_helpers as ir

It's that last line I am looking for

**Comment by thebjorn** [comment]
pydeps doesn't run your program (it only looks at the .pyc files), so any path manipulations you do at runtime will not be seen by pydeps. Perhaps setting the `PYTHONPATH` environment variable will help (or installing ir_lib as a proper package)?

**Comment by jspurestore** [comment]
If we ignore the sys.path.append issue, does it recursively chase the included modules?

**Comment by thebjorn** [comment]
Yes. (but read the docs on `--max-bacon`, `--pylib`, `--pylib-all`, and `--include-missing` for how this is expanded/limited).

**Comment by jspurestore** [comment]
thanks for the fast feedback. The PYTHONPATH was key and it's a great tool.
