### ISSUE TITLE
Question: Dependencies across a multi repo?

### ISSUE THREAD

**Issue by pablojadz** [thebjorn/pydeps#152]
Hello,

I'm new to pydeps, thanks for sharing a good tool.
I have a project that is scattered across many repos and I'm trying to generate a graph across all repos to see who depends on what. 
Is there a way that I can either run `pydeps` from the root folder to all my repos and/or pass a list of repos and construct a joint dependency graph across all of them?

Thanks in advance

**Comment by thebjorn** [comment]
You can probably do it if you create a file that imports all your packages, then run pydeps on it with `--max-bacon` set to something higher than 2 and probably use `--collapse`, or the new and undocumented `--max-module-depth=2`  to make the graph readable. We have an internal tool that does this by using the output of `pydeps --externals` on each package, but it is very tied into our custom infrastructure...

**Comment by pablojadz** [comment]
Hi Bjorn,

Thanks for a quick response. I am doing something very similar to what you suggested, I'm including the steps in case it helps someone else

1. I created a `repo_graph` folder
2. I have `repos` variable with the name of the repos I'm interested in
3. I'm cloning all my repos inside `repo_graph`
4. I'm adding `__init__.py` in the root directory of `repo_graph` and every cloned repo (to make them look like modules)
5. `pydeps  --collapse-target-cluster --only repo_graph ${repos[*]} -T png repo_graph`
