### ISSUE TITLE
*.pyw files should be recognized as valid python source files

### ISSUE THREAD

**Issue by lurid-bogey** [thebjorn/pydeps#155]
Right now only `*.py` files are recognized as valid python source files.
`*.pyw` files should be acceptable as well.

(see file: `pydeps/dummymodule.py`, 
func: `is_pysource`, 
line: `22`)

**Comment by thebjorn** [comment]
Sounds like a good idea...

**Comment by thebjorn** [comment]
@lurid-bogey could you test pydeps v.1.10.24 now available on PyPI?

**Comment by lurid-bogey** [comment]
Works perfect.
