### ISSUE TITLE
Possible to generate a rdeps instead of deps?

### ISSUE THREAD

**Issue by kunaltyagi** [thebjorn/pydeps#157]
Is it possible to have the following invocation:
```
pydeps module_location/ --rdeps --target_file module_location/test_file.py
```

Essentially, I want to find all files that are impacted by some bug or change in the `test_file.py`

I could have missed this feature in my cursory reading of README and options.

**Comment by thebjorn** [comment]
No. Those aren't valid options. I'm not sure I understand what you want, maybe something like "find-usages" in your favorite code editor..? I'd suggest trying pydeps first to see if it will fit your use-case, perhaps investigate the `--show-deps` option if you want to do your own analysis.

**Comment by kunaltyagi** [comment]
> maybe something like "find-usages" in your favorite code editor

I'd love to use an editor, but I need a cli solution. I'm already using pydeps for finding dependencies, and was hoping there was a way to find-usages as well.
