### ISSUE TITLE
The imp module is deprecated

### ISSUE THREAD

**Issue by pawamoy** [thebjorn/pydeps#159]
Following https://github.com/thebjorn/pydeps/issues/136, do you plan on using `importlib` rather than the deprecated `imp` module?

It still generates warning in other people's code, for example:

```
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
File "/media/data/dev/markdown-exec/__pypackages__/3.8/lib/pydeps/mf27.py", line 10, in <module>
    import imp
File "/home/pawamoy/.basher-packages/pyenv/pyenv/versions/3.8.15/lib/python3.8/imp.py", line 31, in <module>
    warnings.warn("the imp module is deprecated in favour of importlib; "
```

I can try and send a PR.

**Comment by thebjorn** [comment]
PRs are always welcome :-)

I see newer versions of modulefinder has punted and just define the constants it used to import from imp - but now with leading underscores (e.g. from py310 modulefinder.py line 19):
```
# Old imp constants:

_SEARCH_ERROR = 0
_PY_SOURCE = 1
_PY_COMPILED = 2
_C_EXTENSION = 3
_PKG_DIRECTORY = 5
_C_BUILTIN = 6
_PY_FROZEN = 7
```
doing something similar will probably get rid of the more difficult dependencies on `imp`.

**Comment by pawamoy** [comment]
Thanks for the guidance. It's more complicated than I thought haha.

**Comment by pawamoy** [comment]
I think this can be closed.
