### ISSUE TITLE
String arguments are not accepted if coming from a config file

### ISSUE THREAD

**Issue by gutipeon** [thebjorn/pydeps#164]
### Current behavior
Passing arguments of type `str`, like `--rankdir`, is only possible via the command line, but not using a config file.

### Expected behavior
Passing arguments of type `str`, like `--rankdir`, shall also be possible using the config file.

### Root cause
When passing an `str` argument via config file, it does not get parsed and the following error is displayed:

```
File "pydeps/arguments.py", line 159, in parse_args
    typfn = typefns[typeval]
KeyError: 'STR'
```

### Solution
The solution is to add `STR` to the `typefns` list in `arguments.py`.

**Comment by thebjorn** [comment]
Hi @gutipeon, and thank you for your interest in pydeps! And thank you very much for the problem analysis. v.1.11.1 has been released on PyPI and should fix this issue.

**Comment by gutipeon** [comment]
Thank you very much @thebjorn for the quick fix, I can confirm the issue is fixed.
