### ISSUE TITLE
Generate indirect dependency relationship.

### ISSUE THREAD

**Issue by happyhebaby** [thebjorn/pydeps#166]
I have a very simple test program that has 3 test files, `s1->s2` meaning s1 import s2.
The test dependency is as following:
`s1->s2, s2->s3`
I used cmd: 
```
pydeps --show-deps --no-output --max-bacon 10 --include-missing .
```
It only generates direct dependency in each `imports` subitem,  is there a way to also include the indirect import/dependency relationship, so that for example s1's imports will be `[s2, s3]` instead of `[s2]`. Or I have to write my own logic to compute that based on the direct import relationship generated by pydeps?

**Comment by thebjorn** [comment]
Hi @happyhebaby  and thank your for your interest in pyedeps.

The terminology you are looking for is the transitive closure of a graph (or the reach-ability matrix).

Pydeps does not include functionality to calculate the transitive closure, but it is easy to create this yourself.

I've created a directory `question` with the following files according to your description:
```
(trclosure) go|c:\srv\tmp\pydeps166> yamldirs question
question:
  __init__.py: ''
  s1.py: |
    from . import s2
  s2.py: |
    from . import s3
  s3.py: ''
```
As you have discovered, pydeps will output the dependency graph with the `--show-deps` flag:
```
...
    "question.s1": {
        "bacon": 1,
        "imported_by": [
            "__main__"
        ],
        "imports": [
            "question",
            "question.s2"
        ],
        "name": "question.s1",
        "path": "C:\\srv\\tmp\\pydeps166\\question\\s1.py"
    },
...
```
and it is easy to transform this into a format that is is expected by a graph algorithm (e.g. a graph represented as a dict mapping nodes to adjacent nodes - or modules to directly importable modules):
```
    import json, os

    # Read the graph from the JSON file.
    os.system('pydeps question --show-deps --no-output --noshow > graph.json')
    with open('graph.json') as f:
        pdgraph = json.load(f)

    # Convert the graph to the format expected by this function.
    graph = {}
    for node in pdgraph:
        graph[node] = pdgraph[node].get('imports', [])
    del graph['__main__']   # this is a root node that pydeps inserts
```
Then you just need a function to calculate the transitive closure, e.g.:
```
def transitive_closure(graph):
    """Return the transitive closure of a graph.

    The transitive closure of a graph is a complete graph in which an edge
    exists between two nodes if and only if there is a path between those two
    nodes in the original graph.

    Parameters
    ----------
    graph : dict
        A graph represented as a dictionary mapping nodes to iterables of
        adjacent nodes.

    Returns
    -------
    dict
        The transitive closure of the graph.

    """
    reachable = {k: tuple(v) for k, v in graph.items()}
    modules = set(reachable.keys())
    while True:
        # Keep looping until we stabilize.
        old_closure = dict(reachable)
        for module in modules:
            tmp = set(reachable[module])
            for v in reachable[module]:
                tmp.update(reachable[v])
            reachable[module] = tuple(tmp)
        if reachable == old_closure:
            return reachable
```
(note: there are better algorithms and implementations for this, e.g. `scipy.sparse.csgraph.floyd_warshall` - with their own unique input graph format, but to keep this relatively simple and self contained I'm using the above..)

Then calling the function with the graph created from the pydeps output (above):
```
    # Compute the transitive closure.
    closure = transitive_closure(graph)

    # Print the result.
    print(json.dumps(closure, indent=2))
```
outputs:
```
{
  "question": [],
  "question.s1": [
    "question.s3",
    "question.s2",
    "question"
  ],
  "question.s2": [
    "question.s3",
    "question"
  ],
  "question.s3": []
}
```
where you can see that `question.1` imports `question.s3` and `question.s2` (and `question`, ie. `question.__init__.py`, which is how Python imports work).

**Comment by happyhebaby** [comment]
Thank you so much @thebjorn for providing such a detailed answer, you are so nice:) Yes this is a typical graph/transit closure algorithm that I am aware of, just not sure if this is a feature that the tool already supports. BTW this looks a pretty common scenario that many module dependency related work may need to use, is it a good idea to add a flag to support it?

**Comment by thebjorn** [comment]
>  is it a good idea to add a flag to support it?

I'm not sure. I'm not opposed to the idea though (i.e. any PR that implements it will probably be merged ;-) )
