### ISSUE TITLE
Is there a way to skip SKIPPING ILLEGAL MODULE_NAME warning?

### ISSUE THREAD

**Issue by happyhebaby** [thebjorn/pydeps#168]
When I run the tool against certain repository, it emits a lot of warnings like the following, is there a flag to turn it off/on? Thanks for the info.
`dummymodule.py:114: WARNING: SKIPPING ILLEGAL MODULE_NAME: ansible.modules.assert`

**Comment by thebjorn** [comment]
There isn't, but that sounds like a good idea...

**Comment by thebjorn** [comment]
Actually... this is from the python logger, so you can remove them by setting the log-level to something higher, e.g.:

    pydeps -L ERROR ...

**Comment by happyhebaby** [comment]
I tried this two days ago and hit some error, didn't have time to look deeper at that time. Just tried again after reading your reply and figured out what's wrong. It needs to be `-LERROR` without the space in between. Thanks a lot for your info!

**Comment by happyhebaby** [comment]
To add a little bit context for everyone, this is for case to handle a large repository where it could emit tons of warnings like this, which could significantly hurt the performance.
