### ISSUE TITLE
Why pydeps pydeps doesn't work?

### ISSUE THREAD

**Issue by deryabozyurt** [thebjorn/pydeps#173]
Greetings,
I'm trying to use the simplest example provided in the documentation.
\>pydeps pydeps
\>No such file or directory: 'pydeps'
Same output on Mac and Windows.
How can make this work?
Kind Regards,
Derya

**Comment by stefan6419846** [comment]
For this to work, you have to clone this repository and run the command from the cloned directory.

**Comment by thebjorn** [comment]
Hi @deryabozyurt and thank you for your interest in pydeps. In the example (`pydeps pydeps`) the first pydeps is the name of the program, the second pydeps is the name of the directory to run on, i.e. if you have a copy of the sources of pydeps that will run pydeps on itself (assuming you are in the directory containing the `setup.py` file).

A complete example to get that to work would be:
```
/home/thebjorn> git clone https://github.com/thebjorn/pydeps.git
/home/thebjorn> cd pydeps
/home/thebjorn/pydeps> pip install -e .
/home/thebjorn/pydeps> pydeps pydeps
```
(notice the dot `.` at the end of the pip install line)

For regular use on your own code, you would do
```
/home/thebjorn> pip install pydeps
/home/thebjorn> cd myproject
/home/thebjorn/myproject> pip install -e .
/home/thebjorn/myproject> pydeps myproject
```
assuming your project had the following structure:
```
myproject
|   `-- myproject
|   `-- __init__.py
|-- README.rst
`-- setup.py
```
(the pip install line might not be needed).

Esentially the command is
```
   parent-directory> pydeps <directory-with-code>
```

**Comment by deryabozyurt** [comment]
Thank you very much Stefan and Bjorn. 
I'm able to get rid of the error. However I'm trying to use pydeps to understand a large project setup similar to https://github.com/dwavesystems/dwave-ocean-sdk and when I follow the workflow above, I get an empty svg file. I suspect the "project" structure is not what pydeps requires and dependent packages may need to be individually cloned.
Do you have any suggestions for me to figure out the dependencies of a project similar to dwave-ocean-sdk?
Kind Regards,
Derya

**Comment by iPAS** [comment]
> Hi @deryabozyurt and thank you for your interest in pydeps. In the example (`pydeps pydeps`) the first pydeps is the name of the program, the second pydeps is the name of the directory to run on, i.e. if you have a copy of the sources of pydeps that will run pydeps on itself (assuming you are in the directory containing the `setup.py` file).
> 
> A complete example to get that to work would be:
> 
> ```
> /home/thebjorn> git clone https://github.com/thebjorn/pydeps.git
> /home/thebjorn> cd pydeps
> /home/thebjorn/pydeps> pip install -e .
> /home/thebjorn/pydeps> pydeps pydeps
> ```
> 
> (notice the dot `.` at the end of the pip install line)
> 
> For regular use on your own code, you would do
> 
> ```
> /home/thebjorn> pip install pydeps
> /home/thebjorn> cd myproject
> /home/thebjorn/myproject> pip install -e .
> /home/thebjorn/myproject> pydeps myproject
> ```
> 
> assuming your project had the following structure:
> 
> ```
> myproject
> |   `-- myproject
> |   `-- __init__.py
> |-- README.rst
> `-- setup.py
> ```
> 
> (the pip install line might not be needed).
> 
> Esentially the command is
> 
> ```
>    parent-directory> pydeps <directory-with-code>
> ```

Probably this explanation should be in the README.md too.

**Comment by thebjorn** [comment]
@iPAS it sort of is there already...

> pydeps finds imports by looking for import-opcodes in python bytecodes (think .pyc files). Therefore, only imported files will be found (ie. pydeps will not look at files in your directory that are not imported). Additionally, only files that can be found using the Python import machinery will be considered (ie. if a module is missing or not installed, it will not be included regardless if it is being imported). This can be modified by using the --include-missing flag.

I'm always happy to merge documentation PRs if you know of a better way to communicate it.
