### ISSUE TITLE
pydeps should remove the hard requirement presence on __init__.py.

### ISSUE THREAD

**Issue by happyhebaby** [thebjorn/pydeps#176]
Python 3.3+ supports Implicit Namespace Packages that allows it to create a package without an __init__.py file, and there are public repository utilizing this feature such as https://github.com/pytest-dev/pytest/tree/main/testing.
When I run the tool against the above sample test directory, it will emit error:
```
	ERROR: [Errno 2] No such file or directory: 'testing'
	(Did you forget to include an __init__.py?)
```
Could you add support for this so that the scan could be completed for such scenario?

**Comment by thebjorn** [comment]
See issue #19

**Comment by happyhebaby** [comment]
Got it. Thanks @thebjorn
