### ISSUE TITLE
Feature request: function matching

### ISSUE THREAD

**Issue by sjkoelle** [thebjorn/pydeps#177]
Love the package - one question however - is it possible to refine the graph structure to look at function invocation rather than import.  Like, if I have functions 1 and 2 in file A that imports file B containing function 3, but only function 1 makes use of function 3, what would it take to represent a graph connecting function 3 to function 1?  Thanks!

**Comment by sjkoelle** [comment]
interesting that pylance also appears to try to solve this issue, but afaic not correctly deal with it all the time
![Screen Shot 2023-04-12 at 3 36 55 PM](https://user-images.githubusercontent.com/6751391/231601246-f47607c3-60cc-481a-aaad-58e665383199.png)

**Comment by thebjorn** [comment]
Hi @sjkoelle and thank you for your interest in pydeps.

I'm afraid call graphs are out of scope of pydeps. There are probably other packages that provide this functionality though (maybe https://pypi.org/project/pycg/ - although I've never tried it).
