### ISSUE TITLE
empty output with multiple dots in file name

### ISSUE THREAD

**Issue by tgpfeiffer** [thebjorn/pydeps#178]
I have a file `neb.en.py` and `pydeps` only produces an empty output when running
```
$ pydeps --show-deps --no-output neb.en.py
```
It's only after renaming the file to `neb.py` that this command produces the correct output.

The docs say that the parameter is a file name, so I think it should work well no matter what characters the file name contains.

**Comment by thebjorn** [comment]
Hi @tgpfeiffer and thank you for your interest in pydeps. 

Yes, that looks like a bug.

**Comment by thebjorn** [comment]
Check out version 1.12.1 available on PyPI.

**Comment by tgpfeiffer** [comment]
Works great, thank you for the quick fix!
