### ISSUE TITLE
pydeps no longer supports files in subdirectories

### ISSUE THREAD

**Issue by vonschultz** [thebjorn/pydeps#179]
# Setup
```shell
mkdir a
touch a/{b,c}.py
echo "import c" >> a/b.py
```

# Old behavior / Expected behavior
Using `pydeps` version 1.11.2, the following works perfectly:
```
$ pydeps a/b.py
```
At `pydeps a/b.py` an image shows up, showing c→b.

# New behavior / Error
Using `pydeps` version 1.12.1, we get the following error:
```
$ pydeps a/b.py

	ERROR: [Errno 2] No such file or directory: 'a/b.py'
	(Did you forget to include an __init__.py?)
```
The program exits with an error. Given the error message, it is worth noting that `touch a/__init__.py` does not make the error go away. Neither does `touch __init__.py`.

**Comment by thebjorn** [comment]
Hi @vonschultz , that sounds like a bug.

**Comment by thebjorn** [comment]
@vonschultz  check out v1.12.2 now on PyPI, it should fix this issue.

**Comment by vonschultz** [comment]
This works with v1.12.2, thanks for the quick fix.

I'm afraid I stumbled onto a new issue, though: https://github.com/thebjorn/pydeps/issues/182
