### ISSUE TITLE
ValueError when running pydeps

### ISSUE THREAD

**Issue by ryanneilyoung** [thebjorn/pydeps#184]
I'm getting the following error:
`Traceback (most recent call last):
  File "/home/ryoung/git/virtualenvs/dws/bin/pydeps", line 8, in <module>
    sys.exit(pydeps())
             ^^^^^^^^
  File "/home/ryoung/git/virtualenvs/dws/lib/python3.11/site-packages/pydeps/pydeps.py", line 150, in pydeps
    _args = dict(iter(_args))
            ^^^^^^^^^^^^^^^^^
ValueError: dictionary update sequence element #0 has length 7; 2 is required`

This is on python 3.11.2 running pydeps 1.12.5. It's a ubuntu lunar wsl2 instance.

**Comment by cosmith** [comment]
It's trying to convert _args to a dict here: https://github.com/thebjorn/pydeps/blob/master/pydeps/pydeps.py#L150 but _args is already a dict.

**Comment by carlosaln** [comment]
We are having the same issue

**Comment by foongminwong** [comment]
Receive the same errors when running `pydeps pydeps` on Windows Python 3.8..

**Comment by ixje** [comment]
Commenting out the line mentioned by @cosmith makes it work here

**Comment by thebjorn** [comment]
Version 1.12.7 now available on PyPI fixes this issue.
