### ISSUE TITLE
Is there a plan to support dependency graphs for Methods and/or Classes?

### ISSUE THREAD

**Issue by noobyogi0010** [thebjorn/pydeps#187]
Hello,

I really loved this library and have recently integrated it into our app. But I wondered if there's a way to generate a similar dependency graph for a particular method or class in a given file or repo.

Thanks.

**Comment by thebjorn** [comment]
Hi @noobyogi0010 and thank you for your interest in pydeps!

pydeps simply looks at the import-pyc codes to find the next file to process, and depending on what you're asking you need dataflow and/or deeper semantic analysis. I'm confident that byte-code parsing is not the way to go for such a problem (it's very fast, but horribly complex). I agree that it would be a very useful tool to have though ;-)
