### ISSUE TITLE
The tests directory is no longer distributed

### ISSUE THREAD

**Issue by penguinpee** [thebjorn/pydeps#188]
Fedora recently updated to Python 3.12 in rawhide (development branch). As part of that all Python packages were rebuild. This brought to light that the tests directory is no longer distributed. Neither the GitHub tarball nor the PyPI tarball contain it.

Since tests are important in order to catch regressions early, e.g. when upgrading to a new Python release, I would like to ask you to include the tests in the tarball either here or on PyPI, preferably both.

Looking at #71 it seems they were included in the past.

**Comment by hroncok** [comment]
The github trarball actually includes tests. It's only the PyPI sdist that does not.

**Comment by thebjorn** [comment]
The packaging code has been stable for "a while" (`setup.py` only lists the package, and the github release uses `ncipollo/release-action@v1`). Can you work with the tarball, or do you want me to include the tests in the PyPI package also? (I don't think any of my PyPI packages include tests...)

**Comment by penguinpee** [comment]
It does not. The package uses the forge macros. So, we are pulling the tarball from GitHub. And it does not contain a tests directory.

Tarball used by spec file: https://github.com/thebjorn/pydeps/archive/v1.12.8/pydeps-1.12.8.tar.gz

This is for the PR updating the package.

The [GitHub tarball for 1.11.1](https://github.com/thebjorn/pydeps/archive/v1.12.8/pydeps-1.11.1.tar.gz) does include it, indeed. However the tarball in the side cache does not. Maybe that was downloaded from PyPI. I don't know. But simple to verify:

```
fedpkg clone pydeps
cd pydeps
fedpkg sources
tar tzf pydeps-1.11.1.tar.gz | grep tests
```

**Comment by hroncok** [comment]
The Feodora package is in an inconsistent state, I've commented the details in https://src.fedoraproject.org/rpms/pydeps/pull-request/2# because I didn't want to bother upstream with Fedora-specific things.

**Comment by thebjorn** [comment]
I just checked the .zip archive for v1.12.8 and it contains tests ;-)  https://github.com/thebjorn/pydeps/archive/refs/tags/v1.12.8.zip 
And also the tarball:  

```
(dev38) go|c:\srv\tmp> gunzip pydeps-1.12.8.tar.gz
'gunzip' is not recognized as an internal or external command,
operable program or batch file.

(dev38) go|c:\srv\tmp> gzip -d pydeps-1.12.8.tar.gz

(dev38) go|c:\srv\tmp> tar xvf pydeps-1.12.8.tar
x pydeps-1.12.8/
x pydeps-1.12.8/LICENSE
x pydeps-1.12.8/PKG-INFO
x pydeps-1.12.8/README.rst
x pydeps-1.12.8/pydeps/
x pydeps-1.12.8/pydeps/__init__.py
x pydeps-1.12.8/pydeps/__main__.py
x pydeps-1.12.8/pydeps/arguments.py
x pydeps-1.12.8/pydeps/cli.py
x pydeps-1.12.8/pydeps/colors.py
x pydeps-1.12.8/pydeps/configs.py
x pydeps-1.12.8/pydeps/depgraph.py
x pydeps-1.12.8/pydeps/depgraph2dot.py
x pydeps-1.12.8/pydeps/dot.py
x pydeps-1.12.8/pydeps/dummymodule.py
x pydeps-1.12.8/pydeps/mf27.py
x pydeps-1.12.8/pydeps/mfimp.py
x pydeps-1.12.8/pydeps/package_names.py
x pydeps-1.12.8/pydeps/py2depgraph.py
x pydeps-1.12.8/pydeps/pycompat.py
x pydeps-1.12.8/pydeps/pydeps.py
x pydeps-1.12.8/pydeps/pystdlib.py
x pydeps-1.12.8/pydeps/render_context.py
x pydeps-1.12.8/pydeps/target.py
x pydeps-1.12.8/pydeps.egg-info/
x pydeps-1.12.8/pydeps.egg-info/PKG-INFO
x pydeps-1.12.8/pydeps.egg-info/SOURCES.txt
x pydeps-1.12.8/pydeps.egg-info/dependency_links.txt
x pydeps-1.12.8/pydeps.egg-info/entry_points.txt
x pydeps-1.12.8/pydeps.egg-info/requires.txt
x pydeps-1.12.8/pydeps.egg-info/top_level.txt
x pydeps-1.12.8/setup.cfg
x pydeps-1.12.8/setup.py

(dev38) go|c:\srv\tmp> cd pydeps

(dev38) go|c:\srv\tmp\pydeps> ll
total 60
-rw-rw-rw-  1 bp 0  2294 2022-11-25 13:44 CHANGELOG.md
-rw-rw-rw-  1 bp 0   166 2022-11-25 13:44 codecov.yml
-rw-rw-rw-  1 bp 0   223 2022-11-25 13:44 dkbuild.yml
drw-rw-rw-  4 bp 0     0 2022-11-25 13:44 docker-images
drw-rw-rw-  3 bp 0     0 2022-11-25 13:44 docs
-rw-rw-rw-  1 bp 0  1287 2022-11-25 13:44 LICENSE
drw-rw-rw-  4 bp 0  4096 2022-11-25 13:44 pydeps
-rw-rw-rw-  1 bp 0    87 2022-11-25 13:44 pytest.ini
-rw-rw-rw-  1 bp 0 19008 2022-11-25 13:44 README.rst
-rw-rw-rw-  1 bp 0   170 2022-11-25 13:44 requirements.txt
-rw-rw-rw-  1 bp 0  1884 2022-11-25 13:44 setup.py
-rw-rw-rw-  1 bp 0   659 2022-11-25 13:44 tasks.py
drw-rw-rw-  2 bp 0  4096 2022-11-25 13:44 tests

(dev38) go|c:\srv\tmp\pydeps> cd tests

(dev38) go|c:\srv\tmp\pydeps\tests> ll
total 76
-rw-rw-rw-  1 bp 0   26 2022-11-25 13:44 __init__.py
-rw-rw-rw-  1 bp 0 2606 2022-11-25 13:44 filemaker.py
-rw-rw-rw-  1 bp 0  456 2022-11-25 13:44 simpledeps.py
-rw-rw-rw-  1 bp 0 2357 2022-11-25 13:44 test_cli.py
-rw-rw-rw-  1 bp 0 1194 2022-11-25 13:44 test_colors.py
-rw-rw-rw-  1 bp 0  518 2022-11-25 13:44 test_cycles.py
-rw-rw-rw-  1 bp 0  648 2022-11-25 13:44 test_dep2dot.py
-rw-rw-rw-  1 bp 0 1161 2022-11-25 13:44 test_dot.py
-rw-rw-rw-  1 bp 0  638 2022-11-25 13:44 test_externals.py
-rw-rw-rw-  1 bp 0  713 2022-11-25 13:44 test_file.py
-rw-rw-rw-  1 bp 0  548 2022-11-25 13:44 test_funny_names.py
-rw-rw-rw-  1 bp 0  654 2022-11-25 13:44 test_json.py
-rw-rw-rw-  1 bp 0  184 2022-11-25 13:44 test_package_names.py
-rw-rw-rw-  1 bp 0  305 2022-11-25 13:44 test_py2dep.py
-rw-rw-rw-  1 bp 0  694 2022-11-25 13:44 test_pyw.py
-rw-rw-rw-  1 bp 0 2990 2022-11-25 13:44 test_relative_imports.py
-rw-rw-rw-  1 bp 0  827 2022-11-25 13:44 test_render_context.py
-rw-rw-rw-  1 bp 0  435 2022-11-25 13:44 test_skinny_package.py
-rw-rw-rw-  1 bp 0 3232 2022-11-25 13:44 test_skip.py

(dev38) go|c:\srv\tmp\pydeps\tests>
```

**Comment by thebjorn** [comment]
The gitlab release .whl and tar.gz contains the same as released on PyPI (i.e. no tests), the Source code (zip) and (tar.gz) do contain the tests.

**Comment by penguinpee** [comment]
> (dev38) go|c:\srv\tmp> tar xvf pydeps-1.12.8.tar
> x pydeps-1.12.8/
> x pydeps-1.12.8/LICENSE
> x pydeps-1.12.8/PKG-INFO
> x pydeps-1.12.8/README.rst
> x pydeps-1.12.8/pydeps/
> x pydeps-1.12.8/pydeps/__init__.py
> x pydeps-1.12.8/pydeps/__main__.py
> x pydeps-1.12.8/pydeps/arguments.py
> x pydeps-1.12.8/pydeps/cli.py
> x pydeps-1.12.8/pydeps/colors.py
> x pydeps-1.12.8/pydeps/configs.py
> x pydeps-1.12.8/pydeps/depgraph.py
> x pydeps-1.12.8/pydeps/depgraph2dot.py
> x pydeps-1.12.8/pydeps/dot.py
> x pydeps-1.12.8/pydeps/dummymodule.py
> x pydeps-1.12.8/pydeps/mf27.py
> x pydeps-1.12.8/pydeps/mfimp.py
> x pydeps-1.12.8/pydeps/package_names.py
> x pydeps-1.12.8/pydeps/py2depgraph.py
> x pydeps-1.12.8/pydeps/pycompat.py
> x pydeps-1.12.8/pydeps/pydeps.py
> x pydeps-1.12.8/pydeps/pystdlib.py
> x pydeps-1.12.8/pydeps/render_context.py
> x pydeps-1.12.8/pydeps/target.py
> x pydeps-1.12.8/pydeps.egg-info/
> x pydeps-1.12.8/pydeps.egg-info/PKG-INFO
> x pydeps-1.12.8/pydeps.egg-info/SOURCES.txt
> x pydeps-1.12.8/pydeps.egg-info/dependency_links.txt
> x pydeps-1.12.8/pydeps.egg-info/entry_points.txt
> x pydeps-1.12.8/pydeps.egg-info/requires.txt
> x pydeps-1.12.8/pydeps.egg-info/top_level.txt
> x pydeps-1.12.8/setup.cfg
> x pydeps-1.12.8/setup.py

I don't see a tests directory listed for the tarball.

> Can you work with the tarball

Yes, I can work with the GitHub tarball.

> The gitlab release .whl and tar.gz contains the same as released on PyPI (i.e. no tests), the Source code (zip) and (tar.gz) do contain the tests.

Well, what is downloaded and what I checked are the GitHub and PyPI release tarballs. I could probably check to see if we can use the source tarball. But if it's easy to include tests in the GitHub release tarball, I'd prefer that.

**Comment by penguinpee** [comment]
Hold on. It seems we are using the source tarball after all. I must have made a mistake when uploading to the side cache. So, we should be good without any modifications.

Sorry for all the fuzz.

**Comment by thebjorn** [comment]
Lolz. Well, 1.12.9 is out and it contains the tests :-)

**Comment by penguinpee** [comment]
Thanks for the quick action. It doesn't hurt. I will need to step away from the keyboard for a bit. I must have taken a wrong turn somewhere. My apologies for all the fuzz.

But it's all settled now. I've updated to 1.12.9 right away and made sure everything is in place. Feel free to revert your changes again, if you prefer.

I did see an error running tests with the 1.12.9 release. I'll look into it and file a new issue if it turns out to be an upstream issue, not a Fedora quirk.

**Comment by thebjorn** [comment]
There is an mf directory containing snapshots of the standard python modulefinder module at various versions (including the 2.7 version which is causing your issue). They're just stored for reference they're not imported anywhere... Looks like your build step is trying to compile everything?

**Comment by thebjorn** [comment]
Excluding files/directories from packaging was a bit more trouble than I anticipated, so I've moved the pydeps/mf directory to docs. Version 1.12.10 will be available on PyPI/github as soon as CI/CD har run.

**Comment by penguinpee** [comment]
> Excluding files/directories from packaging was a bit more trouble than I anticipated, so I've moved the pydeps/mf directory to docs.

With [`packages_find()`](https://github.com/thebjorn/pydeps/compare/v1.12.8...v1.12.9#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7) introduced in 1.12.9 the `tests` directory will be included and installed as a top level module. There's several options to make that work:

1. Remove the `packages` option entirely. Enables autodiscovery, which will exclude tests by default.
2. Add `include=['pydeps*']` in `packages_find()`
3. Add `exclude=['tests*']` in `packages_find()`

With `pydeps/mf` moved to docks, that should be all. If you wanted to exclude that directory in it's original place, I'd go for option 3 and expand the exclude list: `exclude=['tests*', 'pydeps.mf*']`.

Let me know what you prefer and I can provide a patch.

**Comment by thebjorn** [comment]
The problem I was having was that `python -m build` didn't pay attention to the `packages_find(exclude=...)` - it may well be because I was "doing it wrogn". (I was using `python setup.py sdist bdist_wheel` previously.

Upon closer inspection, the tar.gz file contains the tests, but the .whl file does not (with `packages_find(exclude=["tests*"])`), so I'm guessing that is correct.

Version 1.12.12 is available on PyPI and github with this setup.

**Comment by penguinpee** [comment]
`exclude` and `include` are globs. The asterisk is easily overlooked and forgotten making the glob fail. I've been there... :wink:
