### ISSUE TITLE
feature: exclude externals deps

### ISSUE THREAD

**Issue by elanzini** [thebjorn/pydeps#193]
Thanks @thebjorn for the great work!

Is it feasible to add an additional arg `--exclude-external` that allows to exclude external deps and only look at imports for internal modules?

I tried using the `--only` flag but without success, maybe I am doing it wrong running:

`pydeps --show-deps --only /path/to/app --no-output app`

**Comment by thebjorn** [comment]
Try:
```
> cd /path/to
> pydeps --only app --show-deps app
```
`MODULE_PATH` in the docs is a dotted/importable name.

**Comment by elanzini** [comment]
That does the trick, thank you!

**Comment by anilbey** [comment]
Hi I need the same feature but when I try the following 
```bash
❯ pydeps --only app --deps-output app_deps.svg    
```
I get this error below
```
pydeps: error: the following arguments are required: fname
```

Am I using it wrong?

**Comment by thebjorn** [comment]
@anilbey you must tell pydeps where to start looking, i.e. probably (notice the extra `app` at the end)
```
❯ pydeps --only app --deps-output app_deps.svg  app  
```

**Comment by anilbey** [comment]
Great, thanks a lot @thebjorn
