### ISSUE TITLE
Dashes in input filename lead to empty output

### ISSUE THREAD

**Issue by holzkohlengrill** [thebjorn/pydeps#24]
```bash
$ pydeps.exe -o out.svg my-script.py
dummymodule.py:113: WARNING: SKIPPING ILLEGAL MODULE_NAME: my-script
```

Leads to an empty file (no image content) and shows a warning. However this works fine:

```bash
$ pydeps.exe -o out-new.svg myscript.py
```

Output can contain dashes. Input files not. Seems like a bug

**Comment by thebjorn** [comment]
Hi Marcel and thank you for your interest in Pydeps.

I'll agree that it is a bug, however it's something that is difficult for pydeps to work around right now. The main use-case for pydeps is to find dependencies for a package, and to find all modules in the package it creates a dummy file that imports all of them. Files with dashes cannot be imported in the naive way that is used now - and using e.g. `importlib.import_module` doesn't leave the right import-bytecodes for modulefinder to detect...

**Comment by thebjorn** [comment]
(notes)
`importlib.import_module` doesn't work:
```
(dev) go|c:\srv\tmp\issue24> cat myscript.py
import importlib
importlib.import_module("bar")

(dev) go|c:\srv\tmp\issue24> cat bar.py

(dev) go|c:\srv\tmp\issue24> pydeps --noshow --show-deps myscript.py
{
    "__main__": {
        "bacon": 0,
        "imports": [
            "myscript"
        ],
        "name": "__main__",
        "path": null
    },
    "myscript": {
        "bacon": 1,
        "imported_by": [
            "__main__"
        ],
        "name": "myscript",
        "path": "c:\\srv\\tmp\\issue24\\myscript.py"
    }
}
```
regular import works:
```
(dev) go|c:\srv\tmp\issue24> emacs myscript.py

(dev) go|c:\srv\tmp\issue24> cat myscript.py
import bar


(dev) go|c:\srv\tmp\issue24> pydeps --noshow --show-deps myscript.py
{
    "__main__": {
        "bacon": 0,
        "imports": [
            "myscript"
        ],
        "name": "__main__",
        "path": null
    },
    "bar": {
        "bacon": 2,
        "imported_by": [
            "myscript"
        ],
        "name": "bar",
        "path": "c:\\srv\\tmp\\issue24\\bar.py"
    },
    "myscript": {
        "bacon": 1,
        "imported_by": [
            "__main__"
        ],
        "imports": [
            "bar"
        ],
        "name": "myscript",
        "path": "c:\\srv\\tmp\\issue24\\myscript.py"
    }
}
```
`__import__` doesn't work:
```
(dev) go|c:\srv\tmp\issue24> cat myscript.py
__import__('bar')

(dev) go|c:\srv\tmp\issue24> pydeps --noshow --show-deps myscript.py
{
    "__main__": {
        "bacon": 0,
        "imports": [
            "myscript"
        ],
        "name": "__main__",
        "path": null
    },
    "myscript": {
        "bacon": 1,
        "imported_by": [
            "__main__"
        ],
        "name": "myscript",
        "path": "c:\\srv\\tmp\\issue24\\myscript.py"
    }
}
```

**Comment by NicolasCARPi** [comment]
I believe this should be closed as `wontfix` because dashes in modules names are kinda illegal. So user should rename their file, and this tool should not have to deal with this, because as author showed, it is not trivial to do. My 2 cents.

[![2020-04-09-183416_469x120_scrot](https://user-images.githubusercontent.com/3043706/78918471-c3f95c80-7a90-11ea-8f49-834b4eec4512.png)](https://stackoverflow.com/a/37831973)

**Comment by holzkohlengrill** [comment]
I partly agree. In some cases it is illegal (like when importing modules). However since it is theoretically possible to have Python files named like that I expect pydeps to work for those cases too.

A sanity check paired with a descriptive error message would be a good (intermediate-term) workaround. However this could affect user experience in a negative way.

**Comment by prasanta2018** [comment]
> ```shell
> $ pydeps.exe -o out.svg my-script.py
> dummymodule.py:113: WARNING: SKIPPING ILLEGAL MODULE_NAME: my-script
> ```
> 
> Leads to an empty file (no image content) and shows a warning. However this works fine:
> 
> ```shell
> $ pydeps.exe -o out-new.svg myscript.py
> ```
> 
> Output can contain dashes. Input files not. Seems like a bug

faced exactly same issue. Thanks for the heads up. :)
