### ISSUE TITLE
Pydeps mydir not detecting imports

### ISSUE THREAD

**Issue by Jflick58** [thebjorn/pydeps#25]
Hello, 

So I have the following directory: 

Directory 
       L__init__.py
       L database.py
       L controller.py
       L exceptions.py
       L models.py
       L mainclass.py

If I run pydeps directory, it only seems to detect the database.py file, and then traces the sqlalchemy dependencies in that file. I'm importing all of these files in each other, so there should be a graph of those imports. I saw your example in your documentation, how were you able to trace imports of multiple .py files in the same directory? for example, pydeps.colors and pydeps.depgraph?

**Comment by thebjorn** [comment]
Hi Justin, and thank you for your interest in Pydeps.

Strongly connected modules, i.e. modules that are imported by other modules are automatically included. E.g. if I create a package with empty files, except that the models file includes exceptions:
```
(dev) go|c:\srv\tmp> tree mydir
mydir
|   `-- __init__.py
|   `-- controller.py
|   `-- database.py
|   `-- exceptions.py
|   `-- mainclass.py
    `-- models.py

(dev) go|c:\srv\tmp> cat mydir\models.py
from . import exceptions
```
then
```
(dev) go|c:\srv\tmp> pydeps mydir
```
will create

![mydir](https://user-images.githubusercontent.com/1193143/54217102-49f05000-44eb-11e9-8eb8-cef56aa6a19f.png)

It's arguably a bug that the other modules are not included.

A workaround is to import the missing modules in your `__init__.py` file:
```
(dev) go|c:\srv\tmp> cat mydir\__init__.py
from . import (
    controller, database, mainclass, models
)
```
which will let pydeps produce:
![mydir](https://user-images.githubusercontent.com/1193143/54217460-f16d8280-44eb-11e9-91f8-4b3c81ac9f1a.png)

**Comment by Jflick58** [comment]
That helped! thank you!
