### ISSUE TITLE
Feature Request - Output gv dot file only, skip running graphviz

### ISSUE THREAD

**Issue by 13rac1** [thebjorn/pydeps#26]
I want/need to add additional options to the `gv` file before it is parsed by Graphviz with `dot`, so I'd like to just output `--show-dot ` the file and not render it. I thought `--nodot` would do it, but no. I'm not sure what the best configuration option is; open to suggestions. I'm currently using `/dev/null` as a workaround, but it's a waste of CPU:
```
pydeps --max-bacon 2 --noshow --show-dot -o /dev/null udacityu/src > depgraph.gv
sed -i 's/digraph G {/digraph G {\n    nodesep=0.1\n    ranksep=0.2/g' depgraph.gv
dot -T png -x -O depgraph.gv
```

**Comment by thebjorn** [comment]
Hi Brad, and thank you for your interest in pydeps.

Do I understand you correctly that all you want is a `--no-output` flag that prevents the writing of the ".svg" file?

(Note: it should be sufficient for such a flag to branch at the rest of the function here: https://github.com/thebjorn/pydeps/blob/master/pydeps/pydeps.py#L42)

ps: you can probably simplify your regex a bit by removing the `/g`:
```
(dev) go|c:\github\pydeps> pydeps pydeps --max-bacon=1 --show-dot --noshow | sed "s/{/{\n    nodesep=0.1\n    ranksep=0.2/"

digraph G {
    nodesep=0.1
    ranksep=0.2
    concentrate = true;
    rankdir = TB;
    ...
```

**Comment by thebjorn** [comment]
Version 1.7.2 includes a `--no-output` flag, so your command line would be:

    pydeps --max-bacon 2 --no-output --show-dot udacityu/src > depgraph.gv

hth
