### ISSUE TITLE
Option to include a module and exclude everything else

### ISSUE THREAD

**Issue by dibsonmuad** [thebjorn/pydeps#36]
Is there a way to include a particular path and exclude all other paths in the dependency check?

**Comment by thebjorn** [comment]
I just pushed version 1.8.2 which includes a new flag `--only` which takes module paths to include. Everything else is excluded. Usage:
```
pydeps mymodule --only mymodule.submodule_1 mymodule.submodule_2
```

**Comment by dibsonmuad** [comment]
Just tested it. Works great! Perfect :)
