### ISSUE TITLE
Make connection lines highlightable

### ISSUE THREAD

**Issue by Tomasito665** [thebjorn/pydeps#38]
Hi there! First of all, thanks for creating this package. It's awesome.

For large projects, though, the graph can get a bit chaotic. It would be very helpful to be able to click on a line in the browser and make it highlight so that we can see where it connects to (e.g., as PyCharm does with DB UML visualisations). To illustrate the problem, bellow follows a screenshot of the `pydeps` output for a project I'm working on.

![image](https://user-images.githubusercontent.com/12563382/67760440-a1730a00-fa41-11e9-8c83-ff5236614839.png)

Thanks!

**Comment by miketheman** [comment]
@thebjorn Thanks for making an example! I'd consider that the resulting highlight allows a user to follow a path - even if they have to mouse over and move a little bit to find the next connection - seems like a worthwhile addition, if it's not too hard.

**Comment by thebjorn** [comment]
Hi @miketheman, no it's not hard -- it's basically checking that output file type is .svg and then:
```
txt = open(svgfile).read().replace('</title>', '</title><style>.edge>path:hover{stroke-width:10;stroke:hotpink;}</style>')
open(svgfile, 'w').write(txt)
```
with proper file handling of course (and maybe not hotpink...), and probably a way to turn it on/off with a flag.

If someone wants to make a PR that would be super-cool -- if not I'll get to it soon'ish.

**Comment by thebjorn** [comment]
Added (without a flag) in v1.8.5.
