### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by exhuma** [thebjorn/pydeps#4]
Any chance to port this to Python 3?

**Comment by thebjorn** [comment]
Eventually, but I'll probably not get to it until we convert to Py3 internally - ie. not in the next 12-24 months.

Patches are always welcome.  The only non-obvious part should be the fix in https://github.com/thebjorn/pydeps/commit/6fce568cd947f3555f247009b32653373bb680c2 which necessitated a vendorized copy of the `modulefinder` std module. I imagine you'd need a copy of Py3's similarly named module if they haven't made similar changes (it's not needed for regular `modulefinder` usage).

**Comment by eight04** [comment]
Ref: #9
