### ISSUE TITLE
Additional options: remove package name, and add --version flag

### ISSUE THREAD

**Issue by aroberge** [thebjorn/pydeps#43]
Two suggestions:

1. add a --version flag; not critical, but useful to have when reading the documentation.
2. Add an option to remove the original package name. For example, using pydeps on pydeps, instead of showing a node as `pydeps.colors`, show it as `colors`. I believe that this addition, especially when using the `--keep-target-cluster` option, would make everything much easier to read.

**Comment by thebjorn** [comment]
Hi André, and thank you for your interest in pydeps.

`pydeps` already has a `--version` flag (it's been there since v1.3.0):
```
(dev) go|c:\srv> pydeps --version
pydeps v1.8.6
```

I like your other suggestion...

**Comment by aroberge** [comment]
Sorry about the `--version` flag: I should have tried rather than rely on my (possibly faulty) reading of the documentation (and help).

**Comment by thebjorn** [comment]
Not a problem.  Version 1.8.7 is out with a `--rmprefix` flag that can remove multiple prefixes (see the bottom of the readme for an example). It's a good foundation for implementing more automatic prefix removal later (e.g. the active package name/modules in clusters/etc.)

**Comment by aroberge** [comment]
Just tried the new version. When the prefix is the name of the package, it can lead to an empty node. 
![image](https://user-images.githubusercontent.com/629698/69481205-9c596e80-0de5-11ea-8524-f3e5aec51905.png)

**Comment by aroberge** [comment]
Never mind my previous comment: I had forgotten to add the trailing dot.  It works beautifully, thanks.

**Comment by thebjorn** [comment]
Cool :-)
