### ISSUE TITLE
Possible typo in depgraph2dot.py

### ISSUE THREAD

**Issue by csunday95** [thebjorn/pydeps#46]
When attempting to run pydeps on a file using --show-cycles, a warning is issued by graphviz:

`Warning: using box for unknown shape octacon`

This appears to be a typo in depgraph2dot.py at lines 70 and 114, as I assume the shape name is meant to be `octagon`

I am using

`pydeps v1.8.7`

**Comment by thebjorn** [comment]
Hi @csunday95 and thank you for reporting this bug.  I've pushed version 1.8.8 to PyPI which fixes this issue.
