### ISSUE TITLE
Provide example of code

### ISSUE THREAD

**Issue by CristinaRaileanu** [thebjorn/pydeps#50]
I need to do a call graph using pydeps, but on an executable. So, I think a way to do it is to add code that uses pydeps to make a call graph. The things is, I didn't find any example of how to use it programmatically. Could you, please, provide some. Sorry, if this is similar to other issues.

**Comment by thebjorn** [comment]
Good starting points would be https://github.com/thebjorn/pydeps/blob/master/tests/test_skinny_package.py and https://github.com/thebjorn/pydeps/blob/bef746aef505b3a430138b13a4bbacc85cb6e2a2/pydeps/pydeps.py#L136  If you have any specific questions I can try to answer them...

**Comment by CristinaRaileanu** [comment]
still not very clear how should I call it from the code. As I understand inp is the target file and args is a dictionary with flags. I am tried to do this:
```inp = Target('src/fov/applicationWindow.py')
    args = {"max-bacon": 4,
           "only": "src.ps. src.fov. src.pcm.",
           "rmprefix": "src.ps. src.fov. src.pcm."}
    _pydeps(inp, args)```
but gives me this error:
``` TypeError: _pydeps() takes exactly 1 argument (2 given)```

**Comment by thebjorn** [comment]
Ah, ok.  Something like this should work:
```
import os
from pydeps.pydeps import _pydeps
from pydeps.target import Target
import pydeps.cli

FNAME = 'callpydeps.py'
OUT_FNAME = os.path.join(os.getcwd(), 'callpydeps.svg')
```
the output should be an absolute'ish path.

It's usually easier to let pydeps parse the args (note the format and the .split())
```
args = pydeps.cli.parse_args("""
    {fname}
    -o {output}
    --max-bacon=4
""".format(
    fname=FNAME,
    output=OUT_FNAME,
).split())
```
You _can_ create your own arg-dict, but perhaps print the one returned from cli.parse_args to see what is expected...
```
print("ARGS:", args)

_pydeps(
    Target(args['fname']),
    **args
)
```
The filename needs to be wrapped in a pydeps.target.Target class, and the args should be passed with the double-star (`**`) notation.

You should get a graph if you put the above in a file named `'callpydeps.py'` and run it.

**Comment by CristinaRaileanu** [comment]
Thank you very much
