### ISSUE TITLE
Reading directory names

### ISSUE THREAD

**Issue by alexgabel** [thebjorn/pydeps#53]
Hi,

I'm having an issue running pydeps on directories. When I run 'pydeps file.py' I get a perfectly good svg file. Directory names, on the other hand, don't seem to work and I get the following:
```
  File "/opt/anaconda3/lib/python3.7/site-packages/pydeps/dummymodule.py", line 70, in __init__
    for fname in os.listdir(target.dirname):
FileNotFoundError: [Errno 2] No such file or directory
```
What have I done wrong?

Thanks,
Alex

**Comment by thebjorn** [comment]
Not much information to go on, my guess would be that the directory doesn't have an `__init__.py` file..?

**Comment by alexgabel** [comment]
All right, thanks! But now I get "WARNING: SKIPPING ILLEGAL MODULE_NAME" for each script...

**Comment by thebjorn** [comment]
For `pydeps` to analyze a file it must be importable. Importable filenames cannot e.g. have dashes (`-`), start with a number etc.
