### ISSUE TITLE
Release 1.9.0 its ready?

### ISSUE THREAD

**Issue by lbazan** [thebjorn/pydeps#54]
Hi @thebjorn 

Release 1.9.0 its ready?

I see that the release notes says that version 1.9.0 was released but I do not see it in the tags or in the release to download it.

And in pypi.org it lacks folders like tests

Cheers,

**Comment by thebjorn** [comment]
Hi @lbazan, and thank you for your interest in pydeps.

Version 1.9.0 is indeed ready, but it looks like I've forgotten to make the gitlab release. It's there now.

The PyPI releases do exclude tests explicitly (see setup.py) this is intended.

**Comment by lbazan** [comment]
works! 

Thanks!
