### ISSUE TITLE
Update docs with need of installing project dependencies before running pydeps

### ISSUE THREAD

**Issue by fabiosangregorio** [thebjorn/pydeps#58]
Hi, it's me again :)

I've wasted a massive amount of time today because I was trying to set up a Github Action to automatically generate the dependency graph of my project and commit it to the repository, but every time I tried, the graph generated from the CI was different from what I had on my machine. In particular, external dependencies were not shown. Instead, only my project's modules were shown, despite having `max_bacon=3`.

After a couple of hours, it turns out that pydeps needs to have the project's dependencies installed in the environment before running, otherwise it will not catch those imports.

Doing a `pip install -r requirements.txt` before running pydeps fixed the issue. 

I have not seen this required in the documentation, and since the only thing my Github Workflow is doing is generate the graph, I did not install the requirements. Can we add this to the docs for future reference?

**Comment by thebjorn** [comment]
Hmm.. I see the `--include-missing` flag is in the help but not the docs...

**Comment by thebjorn** [comment]
See changes in https://github.com/thebjorn/pydeps/commit/8c9afdbf7f9db54c709cb96d2dd5e40c30d41906
