### ISSUE TITLE
fails to build with python 3.9.0a6

### ISSUE THREAD

**Issue by lbazan** [thebjorn/pydeps#60]
pydeps fails to build with Python 3.9.0a6.

version = '3.9'

    def get_canonical_version(version):
    
        if version in long_versions:
            version = ".".join(version.split(".")[:2])
        elif version not in short_versions:
>           raise ValueError("No such version: {}".format(version))
E           ValueError: No such version: 3.9

**Comment by thebjorn** [comment]
I don't think that is a pydeps issue, but hard to say since you don't include the traceback...
