### ISSUE TITLE
README: isolated venv install

### ISSUE THREAD

**Issue by jhermann** [thebjorn/pydeps#68]
Want a PR for this? (or apply the diff directly)

```diff
--- a/README.rst
+++ b/README.rst
@@ -28,2 +28,7 @@ How to install

+If you prefer an **isolated and easily removable venv installation**,
+consider using `dephell jail install pydeps`_ instead.
+
+.. _`dephell jail install pydeps`: https://dephell.readthedocs.io/cmd-jail-install.html
+
 Basic Usage
```

**Comment by thebjorn** [comment]
While dephell looks cool, you would need to include the install instructions for dephell as well (which are surprising for windows users). Everyone knows what `pip install ...` does, and I'm thinking that users that want to use dephell (or virtualenvwrapper, or any of the other ways of installing or isolating python packages) will know how to translate `pip install ...` into their tool of choice.
