### ISSUE TITLE
Catch missing graphviz

### ISSUE THREAD

**Issue by goetzk** [thebjorn/pydeps#7]
Hi,
I'm aware the docs mention that graphviz is required, but it would be much nicer to see a reminder of that fact instead of a backtrace :)

thanks,
kk

**Comment by thebjorn** [comment]
That sounds reasonable.  Do you have the traceback you got?

**Comment by thebjorn** [comment]
Version 1.4.0 has a fix for this (errno == 2 on both windows and linux whenever dot couldn't be found on my systems..)
