### ISSUE TITLE
Installation through conda

### ISSUE THREAD

**Issue by pranav-s** [thebjorn/pydeps#83]
Hi,
Thanks for all the great work in building this library. Is there any plan to support installation through conda?

**Comment by thebjorn** [comment]
Hi @pranav-s, and thank you for your interest in pydeps.

I don't use conda so I hadn't thought about it... Sounds like a good idea though.

**Comment by mbillingr** [comment]
Hi there!

I just started using pydeps (it's amazing!)... and installed it through conda.
Apparently, somebody has already put it on conda-forge:

```
$ conda search pydeps
Loading channels: done
# Name                       Version           Build  Channel
pydeps                       1.10.12    pyhd8ed1ab_0  conda-forge
```
