### ISSUE TITLE
How to exclude installed modules in "site-packages"?

### ISSUE THREAD

**Issue by rudaoshi** [thebjorn/pydeps#84]
I only want to see the calling graph for my own codes.

**Comment by thebjorn** [comment]
Hi Rudaoshi, and thank you for your interest in pydeps. Please note that pydeps gives you the import graph (not the calling graph). There is no explicit flag to exclude site-packages, but perhaps the `--cluster` flag does what you want?

**Comment by arita37** [comment]
You can create of list of module from "sites_packages" and using as excluding list.
