### ISSUE TITLE
Can't call method "get_value" on an undefined value at /usr/bin/mimeopen line 159.

### ISSUE THREAD

**Issue by axsaucedo** [thebjorn/pydeps#85]
I am getting the error:
```
Error: no "view" mailcap rules found for type "image/svg+xml"
Can't call method "get_value" on an undefined value at /usr/bin/mimeopen line 159.
```

When running pydeps, is this a known issue?

**Comment by thebjorn** [comment]
Sorry for the late reply. That sounds like an OS issue with opening the resulting .svg file... (you can specify this program explicitly with the `--display PROGRAM` option.
