### ISSUE TITLE
Dependency on outdated python 3.4

### ISSUE THREAD

**Issue by eligne-pro** [thebjorn/pydeps#88]
setup.py requires python < 3.4, which is obsolete.
Could it be possible to remove this constraint, to use the scanned project's own python version instead?

**Comment by thebjorn** [comment]
Hi @eligne-pro and thank you for your interest in pydeps. the line in setup.py:

    'enum34; python_version < "3.4"',

just says that if your python is less than 3.4, then setup needs the enum34 package as well.
