### ISSUE TITLE
Option to flip module order

### ISSUE THREAD

**Issue by ghost** [thebjorn/pydeps#97]
Currently, the main Module (the whole package/initial __main__) is showed at the bottom of all Dependencies and the Sub-Modules are stacked on these. To get an overview for my Package I have to start at the end. An option would be nice to show the Main-Module at the start and show the dependencies below (as im Reading a Page from top to bottom, not the other way).
So Instead of:
![image](https://user-images.githubusercontent.com/78810552/126788857-683aacd0-9147-40e3-a9ea-2e1e48be654c.png)

I´d prefer:
![image](https://user-images.githubusercontent.com/78810552/126789014-62cbc966-afec-4ce0-b45e-b65ccfa6e4b9.png)

**Comment by thebjorn** [comment]
Hi @epg-horvath and thank you for your interest in pydeps.

I'm open to a PR for this. It should be under an option named `--top-down` (or better). This option must implicitly set `--reverse`.
The option should change `self.rankdir` to `"TB"` even when `self.reverse` is `True`.  `top_down=False` should probably be added to the `RenderContext` ctor and set as an instance variable.

The relevant line is https://github.com/thebjorn/pydeps/blob/37aaa3d99fcb380bd06134d272dd50bffd1f0060/pydeps/render_context.py#L35

As a hack, you can achieve the result with something like (here calling pydeps on pydeps itself on a windows machine with gnuwin32 installed):
```
pydeps --reverse --show-dot --no-show pydeps | sed -e "s/rankdir = BT/rankdir = TD/g" > tmp.dot && dot -Tpng -o tmp.png tmp.dot && start tmp.png
```
giving:
![tmp](https://user-images.githubusercontent.com/1193143/126950240-d42f7568-0466-4453-8798-0a88b52c2b28.png)
