### ISSUE TITLE
ERROR: [Errno 2] No such file or directory: 'foo'

### ISSUE THREAD

**Issue by poneill** [thebjorn/pydeps#98]
pydeps v1.9.13 will produce the somewhat opaque error message `ERROR: [Errno 2] No such file or directory: 'foo'` when run in a directory `foo` that does not contain an `__init__.py`.  

It might be more ergonomic for the error message to hint at this problem, e.g. `ERROR: [Errno 2] No such file or directory: 'foo': (Is your module missing an __init__.py?)`

Happy to PR if helpful.

**Comment by thebjorn** [comment]
Hi Patrick, and thank you for your interest in pydeps.

PRs are always very welcome :-)

**Comment by thebjorn** [comment]
Fixed in PR #99 and published as 1.9.14.
